name: CRON Scheduled Web UI Test

on:
  schedule:
  - cron: '*/5 * ? * *' # Every 5 min
#   - cron: '0 10 * * ?'  # Every day at 10.00 UTC
  push:
    branches:
    - web_UI_tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Run tests
        run: mvn clean test -Dtest=com/qaprosoft/carina/demo/WebSampleTest#testModelSpecs
