name: Java CI with Maven

on:   
  workflow_dispatch:

jobs:
  build:
  
    runs-on: macos-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install and start Appium
      run: |
        npm install -g appium@1.22
        appium -v
        appium &>/dev/null &
        
    - name: Set up Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        profile: Nexus 6
        arch: x86_64
        force-avd-creation: false
        avd-name: macOS-avd-x86_64-31
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: mvn clean compile test -Dtest=ylevchenko/gfit/android/MainPageTest.java
